
db:
    image: percona
    volumes:
        - ./mysql:/var/lib/mysql
    env_file: conf/mysql

redis:
    image: redis:alpine

mailcatch:
    image: mailhog/mailhog

php5:
    build: php5
    volumes:
        - ./workspace:/data
        - ${HOME}/.ssh:/data/.ssh:ro
        - ${HOME}/.n98-magerun:/data/.n98-magerun:ro
        - $SSH_AUTH_SOCK:/ssh-agent
    environment:
        SSH_AUTH_SOCK: /ssh-agent

    links:
        - db
        - mailcatch
        - redis
    env_file: conf/blackfire

php7:
    build: php7
    volumes:
        - ./workspace:/data
        - ${HOME}/.ssh:/data/.ssh:ro
        - ${HOME}/.n98-magerun:/data/.n98-magerun:ro
        - $SSH_AUTH_SOCK:/ssh-agent
    environment:
        SSH_AUTH_SOCK: /ssh-agent

    links:
        - db
        - mailcatch
        - redis
    env_file: conf/blackfire

web:
    build: web
    volumes:
        - ./workspace:/data:ro
    links:
        - php5:fpm
        - php5:fpm5
        - php7:fpm7
        - mailcatch
    ports:
        - 80:80
        - 443:443
    env_file: conf/blackfire

